# Generated by Django 2.2.12 on 2020-05-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliosoloimg',
            options={'verbose_name': '2) Portfolio solo img'},
        ),
        migrations.AlterModelOptions(
            name='soloimg',
            options={'verbose_name': '3) Img sin album'},
        ),
        migrations.AddField(
            model_name='soloimg',
            name='fkPortfolioSoloImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotoapp.PortfolioSoloImg'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='static/imagenPortfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliosoloimg',
            name='image',
            field=models.ImageField(upload_to='static/imagenPortfolio'),
        ),
    ]
