# Generated by Django 2.2.12 on 2020-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0002_auto_20200522_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albume',
            options={'verbose_name': '2) Album (solo img horizontal).'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': '7) Contacto'},
        ),
        migrations.AlterModelOptions(
            name='imgalbume',
            options={'verbose_name': '3) Img de los Album'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name': '6) Pack'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '1) Portfolio (solo img vertical).'},
        ),
        migrations.AlterModelOptions(
            name='portfoliosoloimg',
            options={'verbose_name': '4) Portfolio solo img'},
        ),
        migrations.AlterModelOptions(
            name='soloimg',
            options={'verbose_name': '5) Img sin album'},
        ),
        migrations.AlterField(
            model_name='albume',
            name='nombre',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
